# Generated by Django 5.0.6 on 2024-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrodenuncia",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "En revisión"),
                    (1, "En procedimiento"),
                    (2, "Finalizada"),
                ],
                default=0,
                verbose_name="Estado de la denuncia",
            ),
        ),
    ]
