# Generated by Django 4.2.13 on 2024-06-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_registrodenuncia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodenuncia',
            name='causa',
            field=models.IntegerField(choices=[[0, 'Lugar de explotación'], [1, 'Uso y/o contaminación de recursos naturales'], [2, 'Residuos, emisiones e inmisiones']], verbose_name='Causa de conflicto'),
        ),
        migrations.AlterField(
            model_name='registrodenuncia',
            name='estado',
            field=models.IntegerField(choices=[[0, 'En revisión'], [1, 'En procedimiento'], [2, 'Finalizada']], default=0, verbose_name='Estado de la denuncia'),
        ),
    ]
