# Generated by Django 5.0.6 on 2024-06-06 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_category_report_user_reportimage_reportcomment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="status",
        ),
        migrations.RemoveField(
            model_name="report",
            name="user",
        ),
    ]
