# Generated by Django 4.2.13 on 2024-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_registrodenuncia_causa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodenuncia',
            name='consentimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrodenuncia',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='Ingrese titulo de denuncia'),
        ),
    ]
