# Generated by Django 5.0.6 on 2024-06-07 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_remove_report_status_remove_report_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=20, verbose_name="Ingrese titulo de denuncia"
                    ),
                ),
                (
                    "causa",
                    models.IntegerField(
                        choices=[
                            (0, "Lugar de explotación"),
                            (1, "Uso y/o contaminación de recursos naturales"),
                            (2, "Residuos, emisiones e inmisiones"),
                        ],
                        verbose_name="Causa de conflicto",
                    ),
                ),
                (
                    "asunto",
                    models.TextField(max_length=200, verbose_name="Ingrese asunto"),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de ingreso"
                    ),
                ),
                (
                    "consentimiento",
                    models.BooleanField(
                        default=False, verbose_name="Acepto terminos y condiciones"
                    ),
                ),
                (
                    "fecha_evento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del evento"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="geolocation",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="website.report"
            ),
        ),
        migrations.AlterField(
            model_name="reportcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="website.category"
            ),
        ),
        migrations.AlterField(
            model_name="reportcategory",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="website.report"
            ),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="website.report"
            ),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="website.user"
            ),
        ),
        migrations.AlterField(
            model_name="reportimage",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="website.report"
            ),
        ),
    ]
