# Generated by Django 5.0.6 on 2024-06-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_registrodenuncia_consentimiento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrodenuncia",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "En revisión"),
                    (1, "En procedimiento"),
                    (2, "Finalizada"),
                    (3, "Rechazada"),
                ],
                default=0,
                verbose_name="Estado de la denuncia",
            ),
        ),
    ]
