# Generated by Django 5.0.6 on 2024-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_registrodenuncia_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="geolocation",
            name="report",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.RemoveField(
            model_name="reportcategory",
            name="report",
        ),
        migrations.RemoveField(
            model_name="reportcomment",
            name="report",
        ),
        migrations.RemoveField(
            model_name="reportimage",
            name="report",
        ),
        migrations.RemoveField(
            model_name="reportcomment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
        migrations.AlterField(
            model_name="registrodenuncia",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "En revisión"),
                    (1, "En procedimiento"),
                    (2, "Finalizada"),
                    (3, "Rechazada"),
                    (4, "Deshabilitada"),
                ],
                default=0,
                verbose_name="Estado de la denuncia",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Geolocation",
        ),
        migrations.DeleteModel(
            name="ReportCategory",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.DeleteModel(
            name="ReportImage",
        ),
        migrations.DeleteModel(
            name="ReportComment",
        ),
    ]
