# Generated by Django 4.2.13 on 2024-06-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_registrodenuncia_causa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodenuncia',
            name='fecha_evento',
        ),
    ]
