# Generated by Django 5.0.6 on 2024-07-01 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_remove_reportcategory_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RegistroDenuncia",
            new_name="Denuncia",
        ),
    ]
