# Generated by Django 4.2.13 on 2024-06-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_registrodenuncia_fecha_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodenuncia',
            name='imagen',
            field=models.ImageField(default='', upload_to='djangouploads/imagenes'),
        ),
    ]
