# Generated by Django 4.2.13 on 2024-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_registrodenuncia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodenuncia',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='djangouploads/imagenes'),
        ),
    ]
