# Generated by Django 4.2.13 on 2024-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_registrodenuncia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodenuncia',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodenuncia',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
