# Generated by Django 4.2.13 on 2024-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_registrodenuncia_latitude_registrodenuncia_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodenuncia',
            name='fecha_suceso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrodenuncia',
            name='hora_suceso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodenuncia',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='registrodenuncia',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
