# Generated by Django 5.0.6 on 2024-06-12 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_registrodenuncia_fecha_suceso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrodenuncia",
            name="username",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.user",
            ),
        ),
    ]
