# Generated by Django 5.0.6 on 2024-06-12 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_alter_registrodenuncia_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrodenuncia",
            name="username",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.user",
            ),
        ),
    ]
