# Generated by Django 5.0.6 on 2024-06-12 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0019_alter_registrodenuncia_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrodenuncia",
            name="username",
        ),
    ]
